### ISSUE TITLE
@types/testing-library__react"' has no exported member 'waitFor'

### ISSUE THREAD

**Issue by denchen** [testing-library/react-testing-library#610]
- `@testing-library/react` version: `10.0.0`
- `react` version: `16.13.0`
- `node` version: `12.13.0`
- `npm` (or `yarn`) version: `1.21.1`

### Relevant code or config:

```javascript
import {  waitFor } from '@testing-library/react';
```

### What happened:

I get a typescript error:

```
@types/testing-library__react"' has no exported member 'waitFor'.ts(2305)
```

### Reproduction:

I have `@testing-library/react@^10.0.0` and `@types/testing-library__react@^9.1.3` installed. I believe each is the latest version.

My current workaround is to add `// @ts-nocheck` to get my test with `waitFor()` to pass.

**Comment by kentcdodds** [comment]
This will be fixed as soon as this is merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43102 😁

**Comment by bbrinx** [comment]
@kentcdodds it might be better to close issues once they are actually resolved. Open issues have a better visibility for others encountering the same problem

**Comment by kentcdodds** [comment]
You're not wrong, but I like to only keep issues open for as long as they have action items we can take within the project where they are. It helps keep things organized.

**Comment by Dobby89** [comment]
I'm still getting this issue using @testing-library/react@10.0.1

**Comment by tom-sherman** [comment]
Me too. @kentcdodds Could you please reopen this issue?

**Comment by eps1lon** [comment]
We have to bump our dependency on `@types/testing-library__react` once https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43108 is merged. Re-opening since this requires action in this repository.

**Comment by MattShrider** [comment]
@eps1lon Did you mean to re-open this?

**Comment by roychoo** [comment]
i still having the same errors

**Comment by huylocit14054** [comment]
@roychoo, Hi, after I update @types/testing-libary__react to version `10.0.1`, I still got the same error. Inside `@types/testing-libary__react` folder, the package.json` file always reference to the `@types/testing-libary__dom@*` (the newest one). However, as I read my `yarn.lock` I saw `@types/testing-libary__dom@*` always point to the older version (6.0.1 for exp). So I think you may have this problem also. I think you need to modify your yarn.lock file.
The solution I used was `yarn add @types/testing-library__dom@7.0.1`. This somehow fixed my issue.
If not you can remove your node modules and re-install or maybe remove yarn.lock.
Sr for my bad English.

**Comment by tom-sherman** [comment]
@huylocit14054 Installing the types yourself is not an ideal solution IMO while @testing-library/dom already includes these as a dependency, there's a potential for them to get out of sync and cause weird errors. This is very much related to https://github.com/testing-library/react-testing-library/issues/620 and https://github.com/testing-library/dom-testing-library/issues/494

**Comment by huylocit14054** [comment]
> @huylocit14054 Installing the types yourself is not an ideal solution IMO while @testing-library/dom already includes these as a dependency, there's a potential for them to get out of sync and cause weird errors. This is very much related to #620 and [testing-library/dom-testing-library#494](https://github.com/testing-library/dom-testing-library/issues/494)

@tom-sherman, you are totally correct. So as far as I understand, in my yarn.lock file, the version of @types/testing-library__dom@* is not the newest one as it should be. So I need to do something to update it to the newest version. After fixing my yarn.lock, I can remove `@types/testing-library__dom` without any problem. Thank you 👍.

**Comment by nathanbirrell** [comment]
Fixed with `yarn remove @testing-library/react @testing-library/jest-dom && yarn add @testing-library/react @testing-library/jest-dom`

**Comment by panpan-lin** [comment]
Fixed with `npm uninstall @testing-library/react @testing-library/jest-dom && npm install --save-dev @testing-library/react @testing-library/jest-dom`

**Comment by Lagily** [comment]
this issue should definitely be open, I know it's prideful to have little issues open, but for users it's a pain to not be able to see what problems are actually not quite fixed yet :D

**Comment by matassp** [comment]
```
    "@testing-library/react": "10.0.5",
    "@testing-library/jest-dom": "5.9.0",
    "react": "16.13.1",
```
I still get the same error. I've tried all solutions mentioned in this issue, and none helps.

**Comment by samtsai** [comment]
@matassp what version of `@testing-library/dom` is in your `yarn.lock` or `package-lock.json`?

**Comment by nickmccurdy** [comment]
Make sure you're using at least TypeScript 3.8, it's required for `import type`.

**Comment by gugol2** [comment]
> Make sure you're using at least TypeScript 3.8, it's required for `import type`.

As I said when building my app I run npx CRA with the typescript template flag...

And it landed with a package.json with:

```"typescript": "~3.7.2"```

I prefer to rollback and not touch too much what CRA gave me, so I am just descructuring the output of `render`.

**Comment by nickmccurdy** [comment]
What's the exact version of TypeScript you have installed?

**Comment by gugol2** [comment]
~ means the latest patch, so it would never reach 3.8.x
^ meas latest minor or patch version, so if I had the caret symbol it could potentially install the 3.8.x

Anyway my version is 3.7.5

**Comment by nickmccurdy** [comment]
Yea you'll need something like `^3.7.2` or `~3.8.0`. to install at least TypeScript 3.8

**Comment by gugol2** [comment]
I know... and as I already SAID I used npx CRA with the ts template...

I am not going to upgrade @testing-library/react @testing-library/jest-dom and typescript.

All the dependencies should be fine out of the box. 
So I will manage without screen.

Thanks!

**Comment by fire-cracker** [comment]
@gugol2 I have exactly the same issues.

**Comment by gugol2** [comment]
> @gugol2 I have exactly the same issues.

Well, I took that approach at that time.
I don't know if running CRA with npx keeps locking the dependencies just the same today, it's been some time...

Sorry I just checked, last release of CRA is 3.4.1 (2020-03-20)
So I guess it must be the same with a fresh project.

I don't find it that painful to just descructure the output of render.

**Comment by jose920405** [comment]
For new react projects still happens. With last versions of everything.

**Comment by nickmccurdy** [comment]
I believe CRA 4 will fix this

**Comment by RichMatthews** [comment]
still getting this issue

**Comment by kentcdodds** [comment]
CRA 4 hasn't been released yet. Update your version of `@testing-library/react`

**Comment by gugol2** [comment]
> CRA 4 hasn't been released yet. Update your version of `@testing-library/react`

@kentcdodds it is not only about RTL, it complains about other dependencies too...

https://github.com/testing-library/react-testing-library/issues/610#issuecomment-678761385

I tried but in the end I rolled back, IMHO it is not so much pain to just destructure the output of render.

**Comment by gugol2** [comment]
Now CRA 4 is here!!!

https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#400-2020-10-23

"To infinity.... and Beyond"

**Comment by elioenays** [comment]
> @roychoo, Hi, after I update @types/testing-libary__react to version `10.0.1`, I still got the same error. Inside `@types/testing-libary__react` folder, the package.json file always reference to the `@types/testing-libary__dom@*` (the newest one). However, as I read my `yarn.lock` I saw `@types/testing-libary__dom@*` always point to the older version (6.0.1 for exp). So I think you may have this problem also. I think you need to modify your yarn.lock file.
> The solution I used was `yarn add @types/testing-library__dom@7.0.1`. This somehow fixed my issue.
> If not you can remove your node modules and re-install or maybe remove yarn.lock.
> Sr for my bad English.


I solved my problem with that
